### ISSUE TITLE
Character Window crashes when loading a character that has no sprite on its renderer

### ISSUE THREAD

**Issue by Plessy** [black-garden-studios/Hitbox-Studio-Pro#4]
NullReferenceException: Object reference not set to an instance of an object
BlackGardenStudios.HitboxStudioPro.CharacterEditorWindow.RenderSprite (UnityEngine.SpriteRenderer renderer, BlackGardenStudios.HitboxStudioPro.SpritePalette palette, Int32 highlightIndex) (at Assets/99 Third Party/BlackGardenStudios/HitboxStudioPro/Editor/Scripts/CharacterEditorWindow.cs:220)
BlackGardenStudios.HitboxStudioPro.CharacterEditorWindow.OnGUI () (at Assets/99 Third Party/BlackGardenStudios/HitboxStudioPro/Editor/Scripts/CharacterEditorWindow.cs:75)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:232)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MethodBase.cs:115)
UnityEditor.HostView.Invoke (System.String methodName, System.Object obj) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:295)
UnityEditor.HostView.Invoke (System.String methodName) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:288)
UnityEditor.HostView.InvokeOnGUI (Rect onGUIPosition) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:255)

**Comment by cschoenig** [comment]
fixed in 1.1.0
